name: groovysh startup time

on:
  pull_request:

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-slim

    strategy:
      fail-fast: false
      matrix:
        java_version: [ 17, 21, 25 ]

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Download Groovy distribution
      run: wget -q https://www.apache.org/dyn/closer.lua/groovy/5.0.2/distribution/apache-groovy-binary-5.0.2.zip?action=download -O apache-groovy-binary-5.0.2.zip
    - name: Unpack Groovy distribution
      run: unzip -q apache-groovy-binary-5.0.2.zip
    - name: Run groovysh here
      timeout-minutes: 1
      run: sh -x ./groovy-5.0.2/bin/groovysh --evaluate /exit
